apiVersion: v1
kind: Service
metadata:
  name: kub-app
spec:
  type: NodePort
  selector:
    app: kub-app
  ports:
    - protocol: TCP
      port: 8080          # What users access
      targetPort: 3000    # ✅ Where the app actually runs
      nodePort: 30880     # Mapped to EC2 host:8080 via kind-config.yaml

